app:
    name: 'user-registeration'
    responsible: 'gaurav'
scratch_org:
    alias: 'user-registeration-scratchOrg'
    definition_file: 'config/project-scratch-def.json'
    alive: 1
    wait: 30
    dependencies:
        #- 04t3b000000gkdZAAQ
        #- 04t3o000001dBnsAAE
    metadata: 'metadata/unpackaged'
    apex_suite: 'user_Registeration'
package:
    name: 'user-registeration'
    wait: 10
    type: 'Unlocked'
    description: 'This is first package'
    path: 'force-app'
