app:
    name: 'user-registeration'
    responsible: 'gaurav'
scratch_org:
    alias: 'user-registeration-scratchOrg'
    definition_file: 'config/project-scratch-def.json'
    alive: 15
    wait: 30
    dependencies:
        - 04t4W000002ke26QAA #OmniStudio
        #- 04t4W000002kaNAQAY #HealthCloud
        - 04t1E000001AY4lQAG #Contacts & Organizations
        - 04t1E000000gbLrQAI #Households
        - 04t1E00000126xrQAA #Recurring Donations
        - 04t2E000003sm94QAA #Relationships
        - 04t2E000003Dl6wQAC #Affiliations
        - 04t5j000000gyi3AAA #Nonprofit dependency
        - 04t5d000001YvaEAAS #Nonprofit Success Pack
        #- 04t4N000000xBe0QAE #CPQ
    metadata: 'metadata/unpackaged'
    apex_suite: 'user_Registeration'
package:
    name: 'user-registeration'
    wait: 10
    type: 'Unlocked'
    description: 'This is first package'
    path: 'force-app'
