# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: deploy
on:
  issues:
    types:
      - labeled
  pull_request:
    types:
      - labeled
      
jobs:
  label:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: '>=14'
          check-latest: true

      - name: Install Salesforce CLI
        run: |
          npm install sfdx-cli
          node_modules/sfdx-cli/bin/run --version
          node_modules/sfdx-cli/bin/run plugins --core
          
      - name: install yaml parser
        run: pip install -U niet       
        
      - name: Setup ScratchOrg
        if: github.event.label.name == 'deploy'    
        working-directory: ./user-registeration
        run: |
          scratchOrg=$(niet -f json .scratch_org deploy-config.yml)
          def=$(niet .definition_file <<< $scratchOrg)
          alias=$(niet .alias <<< $scratchOrg)
          alive=$(niet .alive <<< $scratchOrg)
          wait=$(niet .wait <<< $scratchOrg)
          apexSuit=$(niet .apex_suite <<< $scratchOrg)
          metadata_path=$(niet .metadata <<< $scratchOrg)
          echo '${{ secrets.MY_DEVHUB }}' >> sfdcCred.json
          ../node_modules/sfdx-cli/bin/run force:auth:sfdxurl:store -f ./sfdcCred.json -d -a devhub
          ../node_modules/sfdx-cli/bin/run force:org:list --json
          ../node_modules/sfdx-cli/bin/run force:org:create -f $def -d $alive -a $alias -w $wait -s
          ../node_modules/sfdx-cli/bin/run force:org:list
          ../node_modules/sfdx-cli/bin/run force:org:display -u $alias --verbose --json >> sfdcSOCred.json
          for el in $(niet -s .dependencies <<< $scratchOrg); do ../node_modules/sfdx-cli/bin/run force:package:install -p ${el} -r -w $wait; done
          ../node_modules/sfdx-cli/bin/run force:package:installed:list
          ../node_modules/sfdx-cli/bin/run force:source:push -f
          if [ $metadata_path ]; then ../node_modules/sfdx-cli/bin/run force:mdapi:deploy -d $metadata_path -w $wait; fi
          if [ $apexSuit ]; then ../node_modules/sfdx-cli/bin/run force:apex:test:run -s $apexSuit -c -v -r human; fi
          ../node_modules/sfdx-cli/bin/run force:user:create -u $alias email=gsaini@borregosolar.com profileName='System Administrator' generatepassword=true
      
       
      - name: retrieve Source
        if: github.event.label.name == 'retrieve'    
        working-directory: ./user-registeration
        run: |
          scratchOrg=$(niet -f json .scratch_org deploy-config.yml)
          def=$(niet .definition_file <<< $scratchOrg)
          alias=$(niet .alias <<< $scratchOrg)
          alive=$(niet .alive <<< $scratchOrg)
          wait=$(niet .wait <<< $scratchOrg)
          apexSuit=$(niet .apex_suite <<< $scratchOrg)
          metadata_path=$(niet .metadata <<< $scratchOrg)
          ../node_modules/sfdx-cli/bin/run force:auth:sfdxurl:store -f ./sfdcSOCred.json -d -a $alias
          ../node_modules/sfdx-cli/bin/run force:org:list --json
          ../node_modules/sfdx-cli/bin/run force:source:pull -f
      
      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
