# This is a basic workflow to elp you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      packageConfig: config
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
            
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: '>=14'
          check-latest: true

      - name: install yaml parser
        run: pip install -U niet       
        
      - name: Directory structure
        working-directory: ./user-registeration
        run: |
          ls -ltr
          niet ".config.ScratchOrg.defination" deploy-config.yml 
          packageConfig=$(niet ".config.ScratchOrg.defination" deploy-config.yml)
          echo $packageConfig
        
      - name: Authenticate against dev hub
        working-directory: ./user-registeration
        run: |
          echo $packageConfig
          echo '${{ secrets.SFDC }}' >> sfdcCred.json
          ls -ltr
          ../node_modules/sfdx-cli/bin/run force:auth:sfdxurl:store -f ./sfdcCred.json -d -a devhub
        
      - name: List Salesforce orgs
        working-directory: ./user-registeration
        run: |
          echo $packageConfig
          ../node_modules/sfdx-cli/bin/run force:org:list --json
        
